env: local
storage:
  host: localhost
  port: 5436
  username: postgres
  password: qwerty
  dbname: postgres
  sslmode: disable
http_server:
  address: localhost:8082
  timeout: 4s
  idle_timeout: 60s